In [2]:
import pandas as pd
import requests
from tqdm import tqdm 
from bs4 import BeautifulSoup
df=pd.read_csv("book_scrapping.csv")
df.head()

,title,rating,stock,img_link,book_link,price
0,A Light in the Attic,Three,In stock,https://books.toscrape.com/../media/cache/2c/d...,https://books.toscrape.com/catalogue/a-light-i...,£51.77
1,Tipping the Velvet,One,In stock,https://books.toscrape.com/../media/cache/26/0...,https://books.toscrape.com/catalogue/tipping-t...,£53.74
2,Soumission,One,In stock,https://books.toscrape.com/../media/cache/3e/e...,https://books.toscrape.com/catalogue/soumissio...,£50.10
3,Sharp Objects,Four,In stock,https://books.toscrape.com/../media/cache/32/5...,https://books.toscrape.com/catalogue/sharp-obj...,£47.82
4,Sapiens: A Brief History of Humankind,Five,In stock,https://books.toscrape.com/../media/cache/be/a...,https://books.toscrape.com/catalogue/sapiens-a...,£54.23

In [8]:
data=[]
for link in tqdm(df["book_link"]):
    res=requests.get(link)
    soup=BeautifulSoup(res.text,"html.parser")
    type_=soup.find("ul",class_="breadcrumb").find_all("a")[2].text
    upc            =soup.find("table",class_="table table-striped").find_all("td")[0].text
    price_x        =soup.find("table",class_="table table-striped").find_all("td")[2].text[1:]
    price_i        =soup.find("table",class_="table table-striped").find_all("td")[3].text[1:]
    tax            =soup.find("table",class_="table table-striped").find_all("td")[4].text[1:]
    quantity       =soup.find("table",class_="table table-striped").find_all("td")[5].text
    review         =soup.find("table",class_="table table-striped").find_all("td")[6]
    data.append([type_,price_x,price_i,tax,upc,review,quantity])

100%|██████████| 1000/1000 [16:20<00:00,  1.02it/s]

In [11]:
upc

'228ba5e7577e1d49'

In [16]:
df1=pd.DataFrame(data,columns=["Category","price_e_tax","price_i_tax","tax","upc","review","qunatity"])
df1.tail()
# df1.to_csv("page_scrapping.csv",index=False)

#adding the dataframe

In [17]:
import pandas as pd 
df_1=pd.read_csv("book_scrapping.csv")
df_2=pd.read_csv("page_scrapping.csv")

In [19]:
df=pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [20]:
df_1.head()

,title,rating,stock,img_link,book_link,price
0,A Light in the Attic,Three,In stock,https://books.toscrape.com/../media/cache/2c/d...,https://books.toscrape.com/catalogue/a-light-i...,£51.77
1,Tipping the Velvet,One,In stock,https://books.toscrape.com/../media/cache/26/0...,https://books.toscrape.com/catalogue/tipping-t...,£53.74
2,Soumission,One,In stock,https://books.toscrape.com/../media/cache/3e/e...,https://books.toscrape.com/catalogue/soumissio...,£50.10
3,Sharp Objects,Four,In stock,https://books.toscrape.com/../media/cache/32/5...,https://books.toscrape.com/catalogue/sharp-obj...,£47.82
4,Sapiens: A Brief History of Humankind,Five,In stock,https://books.toscrape.com/../media/cache/be/a...,https://books.toscrape.com/catalogue/sapiens-a...,£54.23

In [21]:
df_2.head()

,Category,price_e_tax,price_i_tax,tax,upc,review,qunatity
0,Poetry,£51.77,£51.77,£0.00,a897fe39b1053632,<td>0</td>,In stock (22 available)
1,Historical Fiction,£53.74,£53.74,£0.00,90fa61229261140a,<td>0</td>,In stock (20 available)
2,Fiction,£50.10,£50.10,£0.00,6957f44c3847a760,<td>0</td>,In stock (20 available)
3,Mystery,£47.82,£47.82,£0.00,e00eb4fd7b871a48,<td>0</td>,In stock (20 available)
4,History,£54.23,£54.23,£0.00,4165285e1663650f,<td>0</td>,In stock (20 available)

In [25]:
df["title"]                =df_1["title"]
df["Category"]             =df_2["Category"]
df["price_e_tax"]          =df_2["price_e_tax"]
df["price_i_tax"]          =df_2["price_i_tax"]
df["rating"]               =df_1["rating"]
df["tax"]                  =df_2["tax"]   
df["qunatity"]             =df_2["qunatity"]
df["stock"]                =df_1["stock"]
df["book_link"]            =df_1["book_link"]
df["img_link"]             =df_1["img_link"]

In [29]:
# df.to_csv("final_book_scrap.csv",index=False)