In [61]:
import requests 
import pandas as pd
from tqdm import tqdm
from bs4 import BeautifulSoup

In [62]:
link="https://quotes.toscrape.com/"

In [63]:
res=requests.get(link)

In [64]:
# print(res.text)

In [65]:
html=res.text

In [66]:
# df=open("quotes.html","w")
# df.write(html)
# df.close()

In [67]:
soup=BeautifulSoup(res.text,"html.parser")

In [85]:
print(soup.find("span"))

<span class="text" itemprop="text">“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”</span>

In [86]:
data=[]
for sp in soup.find_all("div",class_="quote"):
    quote         =sp.find("span",class_="text").text[1:-1]
    author        =sp.find("small").text[1:-1]
    author_id     =sp.find("a").get("href")
    tags=[]
    for tag in sp.find_all("a", class_="tag"):
        tags.append(tag.text)
    tags          =",".join(tags)
    data.append([quote,author,author_id,tags])

In [70]:
df=pd.DataFrame(data,columns=["quote","author","author_id","tags"])
df

,quote,author,author_id,tags
0,The world as we have created it is a process o...,lbert Einstei,/author/Albert-Einstein,"change,deep-thoughts,thinking,world"
1,"It is our choices, Harry, that show what we tr...",.K. Rowlin,/author/J-K-Rowling,"abilities,choices"
2,There are only two ways to live your life. One...,lbert Einstei,/author/Albert-Einstein,"inspirational,life,live,miracle,miracles"
3,"The person, be it gentleman or lady, who has n...",ane Auste,/author/Jane-Austen,"aliteracy,books,classic,humor"
4,"Imperfection is beauty, madness is genius and ...",arilyn Monro,/author/Marilyn-Monroe,"be-yourself,inspirational"
5,Try not to become a man of success. Rather bec...,lbert Einstei,/author/Albert-Einstein,"adulthood,success,value"
6,It is better to be hated for what you are than...,ndré Gid,/author/Andre-Gide,"life,love"
7,"I have not failed. I've just found 10,000 ways...",homas A. Ediso,/author/Thomas-A-Edison,"edison,failure,inspirational,paraphrased"
8,A woman is like a tea bag; you never know how ...,leanor Roosevel,/author/Eleanor-Roosevelt,misattributed-eleanor-roosevelt
9,"A day without sunshine is like, you know, night.",teve Marti,/author/Steve-Martin,"humor,obvious,simile"

In [ ]:
for i in range(len(df1["author_id"])):

In [71]:
# df.to_csv("quotes.csv",index=False)

In [59]:
data1 =[]
for page in range(1,11):
    link="https://quotes.toscrape.com/page/"+str(page)
    res=requests.get(link)
    soup=BeautifulSoup(res.text,"html.parser")

    for sp in soup.find_all("div",class_="quote"):
        quote         =sp.find("span",class_="text").text[1:-1]
        author        =sp.find("small").text[1:-1]
        author_id     =sp.find("a").get("href")
        tags=[]
        for tag in sp.find_all("a", class_="tag"):
            tags.append(tag.text)
        tags          =",".join(tags)
        data1.append([quote,author,author_id,tags])

In [79]:
df1=pd.DataFrame(data1,columns=["quote","author","author_id","tags"])
# df1.to_csv("new_quotes.csv",index=False)

In [81]:

df1["author_link"]="https://quotes.toscrape.com/"+df1["author_id"]
df1.sample(6)

,quote,author,author_id,tags,author_link
37,Any fool can know. The point is to understand.,lbert Einstei,/author/Albert-Einstein,"knowledge,learning,understanding,wisdom",https://quotes.toscrape.com//author/Albert-Ein...
71,Some people never go crazy. What truly horribl...,harles Bukowsk,/author/Charles-Bukowski,humor,https://quotes.toscrape.com//author/Charles-Bu...
51,Do one thing every day that scares you.,leanor Roosevel,/author/Eleanor-Roosevelt,"attributed,fear,inspiration",https://quotes.toscrape.com//author/Eleanor-Ro...
29,"One good thing about music, when it hits you, ...",ob Marle,/author/Bob-Marley,music,https://quotes.toscrape.com//author/Bob-Marley
86,We are not necessarily doubting that God will ...,.S. Lewi,/author/C-S-Lewis,god,https://quotes.toscrape.com//author/C-S-Lewis
5,Try not to become a man of success. Rather bec...,lbert Einstei,/author/Albert-Einstein,"adulthood,success,value",https://quotes.toscrape.com//author/Albert-Ein...

In [98]:
for i in range (len(df1["author_id"])):
    print(("https"+df1["author_id"])[i])

https/author/Albert-Einstein
https/author/J-K-Rowling
https/author/Albert-Einstein
https/author/Jane-Austen
https/author/Marilyn-Monroe
https/author/Albert-Einstein
https/author/Andre-Gide
https/author/Thomas-A-Edison
https/author/Eleanor-Roosevelt
https/author/Steve-Martin
https/author/Marilyn-Monroe
https/author/J-K-Rowling
https/author/Albert-Einstein
https/author/Bob-Marley
https/author/Dr-Seuss
https/author/Douglas-Adams
https/author/Elie-Wiesel
https/author/Friedrich-Nietzsche
https/author/Mark-Twain
https/author/Allen-Saunders
https/author/Pablo-Neruda
https/author/Ralph-Waldo-Emerson
https/author/Mother-Teresa
https/author/Garrison-Keillor
https/author/Jim-Henson
https/author/Dr-Seuss
https/author/Albert-Einstein
https/author/J-K-Rowling
https/author/Albert-Einstein
https/author/Bob-Marley
https/author/Dr-Seuss
https/author/J-K-Rowling
https/author/Bob-Marley
https/author/Mother-Teresa
https/author/J-K-Rowling
https/author/Charles-M-Schulz
https/author/William-Nicholson
https/author/Albert-Einstein
https/author/Jorge-Luis-Borges
https/author/George-Eliot
https/author/George-R-R-Martin
https/author/C-S-Lewis
https/author/Marilyn-Monroe
https/author/Marilyn-Monroe
https/author/Albert-Einstein
https/author/Marilyn-Monroe
https/author/Marilyn-Monroe
https/author/Martin-Luther-King-Jr
https/author/J-K-Rowling
https/author/James-Baldwin
https/author/Jane-Austen
https/author/Eleanor-Roosevelt
https/author/Marilyn-Monroe
https/author/Albert-Einstein
https/author/Haruki-Murakami
https/author/Alexandre-Dumas-fils
https/author/Stephenie-Meyer
https/author/Ernest-Hemingway
https/author/Helen-Keller
https/author/George-Bernard-Shaw
https/author/Charles-Bukowski
https/author/Suzanne-Collins
https/author/Suzanne-Collins
https/author/C-S-Lewis
https/author/J-R-R-Tolkien
https/author/J-K-Rowling
https/author/Ernest-Hemingway
https/author/Ralph-Waldo-Emerson
https/author/Mark-Twain
https/author/Dr-Seuss
https/author/Alfred-Tennyson
https/author/Charles-Bukowski
https/author/Terry-Pratchett
https/author/Dr-Seuss
https/author/J-D-Salinger
https/author/George-Carlin
https/author/John-Lennon
https/author/W-C-Fields
https/author/Ayn-Rand
https/author/Mark-Twain
https/author/Albert-Einstein
https/author/Jane-Austen
https/author/J-K-Rowling
https/author/Jane-Austen
https/author/Jane-Austen
https/author/C-S-Lewis
https/author/C-S-Lewis
https/author/Mark-Twain
https/author/Mark-Twain
https/author/C-S-Lewis
https/author/J-K-Rowling
https/author/Jimi-Hendrix
https/author/J-M-Barrie
https/author/E-E-Cummings
https/author/Khaled-Hosseini
https/author/Harper-Lee
https/author/Madeleine-LEngle
https/author/Mark-Twain
https/author/Dr-Seuss
https/author/George-R-R-Martin

In [24]:
tags=[]
for tag in sp.find_all("a", class_="tag"):
    tags.append(tag.text)
tags    
",".join(tags)

'humor,obvious,simile'

In [69]:
print(soup.find("span",class_="text").text[1:-1])

The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.

In [82]:
quotes=[]
for quote in soup.find_all("span",class_="text"):
    quotes.append(quote.text[1:-1])

In [83]:

for author in soup.find_all("small"):
    print(author.text[1:-1])

lbert Einstei
.K. Rowlin
lbert Einstei
ane Auste
arilyn Monro
lbert Einstei
ndré Gid
homas A. Ediso
leanor Roosevel
teve Marti

,0,1,2,3
0,The world as we have created it is a process o...,lbert Einstei,/author/Albert-Einstein,"change,deep-thoughts,thinking,world"
1,"It is our choices, Harry, that show what we tr...",.K. Rowlin,/author/J-K-Rowling,"abilities,choices"
2,There are only two ways to live your life. One...,lbert Einstei,/author/Albert-Einstein,"inspirational,life,live,miracle,miracles"
3,"The person, be it gentleman or lady, who has n...",ane Auste,/author/Jane-Austen,"aliteracy,books,classic,humor"
4,"Imperfection is beauty, madness is genius and ...",arilyn Monro,/author/Marilyn-Monroe,"be-yourself,inspirational"
...,...,...,...,...
95,You never really understand a person until you...,arper Le,/author/Harper-Lee,better-life-empathy
96,You have to write the book that wants to be wr...,adeleine L'Engl,/author/Madeleine-LEngle,"books,children,difficult,grown-ups,write,write..."
97,Never tell the truth to people who are not wor...,ark Twai,/author/Mark-Twain,truth
98,"A person's a person, no matter how small.",r. Seus,/author/Dr-Seuss,inspirational
99,... a mind needs books as a sword needs a whet...,eorge R.R. Marti,/author/George-R-R-Martin,"books,mind"